// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgHF6JjVdu1AiB4IKjGls8DUv4kt1ITM',
    appId: '1:154192929027:web:cd13af7336936b8b198936',
    messagingSenderId: '154192929027',
    projectId: 'notas-a17fc',
    authDomain: 'notas-a17fc.firebaseapp.com',
    storageBucket: 'notas-a17fc.appspot.com',
    measurementId: 'G-C3HJZ7E0ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbG1uO0xJVNX37DShmdPRqnl5Rk0Q85L4',
    appId: '1:154192929027:android:c84dfcd0f945d3a2198936',
    messagingSenderId: '154192929027',
    projectId: 'notas-a17fc',
    storageBucket: 'notas-a17fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ptffOW2x6CNiPSYtPunxRxMLa0Turb4',
    appId: '1:154192929027:ios:46dbd538c7533ba1198936',
    messagingSenderId: '154192929027',
    projectId: 'notas-a17fc',
    storageBucket: 'notas-a17fc.appspot.com',
    iosClientId: '154192929027-s2n1ejk678pqc7gg4mtitjiqkmqv384p.apps.googleusercontent.com',
    iosBundleId: 'com.example.drMendoza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ptffOW2x6CNiPSYtPunxRxMLa0Turb4',
    appId: '1:154192929027:ios:46dbd538c7533ba1198936',
    messagingSenderId: '154192929027',
    projectId: 'notas-a17fc',
    storageBucket: 'notas-a17fc.appspot.com',
    iosClientId: '154192929027-s2n1ejk678pqc7gg4mtitjiqkmqv384p.apps.googleusercontent.com',
    iosBundleId: 'com.example.drMendoza',
  );
}
